import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import ThreeView from "../components/ThreeView";
import { Suspense } from "react";
import { Loader } from "@react-three/drei";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Canvas
					camera={{ fov: 75, near: 0.1, far: 1000, position: [0, 0, 5] }}
					shadows
				>
					<Suspense fallback={null}>
						<ThreeView />
					</Suspense>
				</Canvas>
				<Loader
					innerStyles={{ width: "200px" }}
					dataStyles={{ fontSize: 18 }}
				/>
			</main>
		</>
	);
}
